seed: 42
image_size:
  - 384
  - 384

## Acceleration
R: 4
pattern: equispaced
orientation: vertical

## Original NCSN configurations
sampling:
  batch_size: 1
  step_lr: 5e-5
  n_steps_each: 4

data:
  dataset: "mri-mvue"
  image_size: 384
  channels: 2
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 8

model:
  sigma_begin: 232
  num_classes: 2311
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.0066
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128
