anatomy: "brain_T2"
seed: 42
image_size:
  - 384
  - 384
batch_size: 4
denoise_005: true
circle_mask: true

## Paths
model_path: "/content/csgm-mri-ddim/ncsnv2-mri-mvue/logs/mri-mvue/checkpoint_100000.pth"
data_dir: "/content/csgm-mri-ddim/datasets/brain_T2"
maps_dir: "/content/csgm-mri-ddim/datasets/brain_T2_maps"

## Original NCSN configurations
sampling:
  step_lr: 5e-5
  n_steps_each: 4
  mse: 5.

data:
  dataset: "mri-mvue"
  image_size: 384
  channels: 2
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: false
  num_workers: 8

model:
  sigma_begin: 232
  num_classes: 2311
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.0066
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128
